version: "3.8"

services:
  app:
    build: .
    image: dice-game:latest
    container_name: dice-game
    restart: unless-stopped
    labels:
      # Enable Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      # HTTP Routers & Services (HOST from stack env)
      - "traefik.http.routers.betwenus.entrypoints=websecure"
      - "traefik.http.routers.betwenus.rule=Host(`${HOST}`)"
      - "traefik.http.routers.betwenus.tls.certresolver=le"
      - "traefik.http.routers.betwenus.service=betwenus"
      - "traefik.http.services.betwenus.loadbalancer.server.port=80"
      # 10GB request/response body limit for this app's router
      - "traefik.http.routers.betwenus.middlewares=limit@docker"
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=10737418240"
      - "traefik.http.middlewares.limit.buffering.memRequestBodyBytes=200000000"
      - "traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=10737418240"
      - "traefik.http.middlewares.limit.buffering.memResponseBodyBytes=200000000"
    networks:
      - betwenus_internal
      - traefik_proxy

networks:
  betwenus_internal:
    name: betweenus
  traefik_proxy:
    external: true
