// Phase/location/action tables – edit here

const tables = {
  1: {
    name: 'Warm‑up',
    description: 'Non‑genital, low‑pressure exploration, clothing/lingerie optional.',
    locations: {
      1: 'Lips',
      2: 'Ears (Lobes or Outer Shell)',
      3: 'Nape of the Neck',
      4: 'Collarbone',
      5: 'Shoulders',
      6: 'Nipples / Areolas',
      7: 'Chest / Breasts',
      8: 'Inner Arms / Elbow Crease',
      9: 'Inner Wrists',
      10: 'Palms / Fingertips',
      11: 'Belly Button / Navel',
      12: 'Lower Back / Sacrum',
      13: 'Hips / Waist',
      14: 'Buttocks',
      15: 'Perineum',
      16: 'Inner Thighs',
      17: 'Behind the Knees',
      18: 'Feet / Arches',
      19: 'Primary Genitals',
      20: 'Critical Hit: Roller’s choice of location.'
    },
    actions: {
      1: 'Slow hand strokes: Use the full palm and fingers to make slow, steady strokes over the area.',
      2: 'Feather-light fingertips: Use only the very tips of your fingers to barely graze the surface of the skin.',
      3: 'Gentle kneading: Use the heels of your hands to gently squeeze and knead the muscles in a slow rhythm.',
      4: 'Still hand and breath: Rest a warm hand on the area and breathe slowly together, noticing warmth and contact.',
      5: 'Tracing with one finger: Use a single fingertip to trace lines, shapes, or simple patterns on the skin.',
      6: 'Alternating fingers: Alternate between one finger and all fingers to change the feel of the touch.',
      7: 'Soft tapping: Use the pads of your fingertips to make soft, rhythmic taps over the area.',
      8: 'Cupping with the hand: Gently cup the area with your palm and hold, adding tiny movements if it feels good.',
      9: 'Back of the hand: Use the backs of your fingers or hand to stroke the area for a different texture.',
      10: 'Finger circles: Use one or two fingers to draw slow circles of different sizes over the area.',
      11: 'Warm breath: Blow soft, warm air over the area, occasionally pausing to notice how the skin feels.',
      12: 'Kissing: Place slow, simple kisses on the area, without licking or nibbling.',
      13: 'Soft tongue: Use the tongue to slowly trace short lines or small shapes on the area.',
      14: 'Soft lip pressure: Press your closed lips gently against the area, then slowly release.',
      15: 'Light mouth suction: Use lips to create very gentle suction, then release in a slow rhythm.',
      16: 'Butterfly kisses: Gently flutter your eyelashes against the skin around the area.',
      17: 'Foot strokes (if comfortable): Use the underside of your toes or the ball of your foot to make slow, gentle strokes.',
      18: 'Foot tracing: Use the edge of your foot or toes to trace simple lines or shapes over the area.',
      19: 'Toe taps: Use your toes to make soft, rhythmic taps, similar to fingertip tapping.',
      20: 'Critical success: Spend about twice as long on this location, then roll again on the action table to decide how to touch it.'
    }
  },

  2: {
    name: 'Heating up',
    description: 'Breasts/chest and genitals allowed; still low pressure and exploration‑focused.',
    locations: {
  1: 'Mouth: inner lips + tongue (kissing, lip-sucking, gentle biting).',
  2: 'Ears (lobes + inner rim).',
  3: 'Front of neck + under jawline (light kisses, gentle suction).',
  4: 'Nape/hairline + back of neck (small kisses, gentle suction).',
  5: 'Collarbones/clavicle + upper chest (above breast/pec line).',
  6: 'Nipple–areola complex (any gender).',
  7: 'Nipple–areola complex.',
  8: 'Full breast/pectoral mound (including under-breast fold + outer curves).',
  9: 'Lower belly “V”/waistband line leading toward the pubic hairline (external).',
  10: 'Pubic mound/mons + upper groin (external; above genitals).',
  11: 'Inner thighs (highest 1/3) + groin creases close to genitals (external).',
  12: 'Inner thighs + groin creases.',
  13: 'Full butt cheeks + gluteal folds where butt meets thighs.',
  14: 'Lower back/sacrum + top of buttocks.',
  15: 'Perineum (external; between genitals and anus).',
  16: 'Outer vulva only (labia majora / outer genital area; no penetration).',
  17: 'Penis/scrotum (lower shaft + scrotum; no penetration).',
  18: 'Genital ‘edges’ (external): where thighs meet groin + just outside the most sensitive tissue.',
  19: 'Hips/iliac crest + side of hips (the ‘handhold’ area).',
  20: 'Roller’s choice of any Phase 2 location that both partners want to revisit (or reroll).',
},

    actions: {
  1: 'Use a hand to give 20 straight strokes at a steady pace.',
  2: 'Use a hand to give 10 short rapid strokes followed by 10 slow long strokes, then repeat this sequence once.',
  3: 'Use hands to give 15 light brushing strokes, followed immediately by 15 steady rubbing strokes.',
  4: 'Use the mouth and tongue to give 10 slow licks in straight lines, then 10 small circular licks.',
  5: 'Use a hand with lubricant to give 20 loose gliding strokes with a continuous motion.',
  6: 'Use fingers or a toy to move slowly back and forth 15 times, with a brief pause after every fifth motion.',
  7: 'Use genitals to make 20 slow thrusting motions, with a one-second stillness after every fourth thrust.',
  8: 'Use hands, mouth, feet, or genitals to keep a steady rhythm for 30 seconds, then a faster rhythm for 30 seconds, then return to the original steady rhythm for 30 seconds.',
  9: 'Use two body parts at once so that one performs 10 slow strokes while the other performs 10 quick strokes, then swap which is slow and which is quick.',
  10: 'Use hands or genitals to give exactly 10 slow strokes, 10 medium-speed strokes, and 10 fast strokes, in that order.',
  11: 'Use hands, mouth, feet, or genitals to perform a repeating three-step pattern: one slow movement, one medium movement, one fast movement; repeat this pattern 10 times.',
  12: 'While using hands, mouth, feet, or genitals, give 10 strokes and pair each stroke with an exhale or vocal sound.',
  13: 'Use hands, mouth, feet, or genitals to perform the pattern “three light touches followed by one firm touch,” repeated eight times.',
  14: 'Use hands, mouth, feet, or genitals in a “stop-start” pattern: five continuous movements, then one full second of stillness; repeat this cycle 10 times.',
  15: 'For 60 seconds, use hands, mouth, feet, or genitals only in small circular motions at a constant speed.',
  16: 'While using hands, mouth, feet, or genitals, after every 10 movements, pause briefly, give a “red/yellow/green” signal, then resume at the same pace for the next 10 movements.',
  17: 'Repeat the previous action, but increase the size of each movement slightly for each set of 10 movements.',
  18: 'Use hands, mouth, feet, or genitals to repeat a simple pattern of five identical movements, followed immediately by five quicker, shorter movements; complete this full pattern four times.',
  19: 'Use hands, mouth, feet, or genitals to perform 30 tracing movements, each lasting about one second, without pausing.',
  20: 'Use hands, mouth, feet, or genitals to perform a four-step sequence—slow stroke, medium stroke, fast stroke, brief stillness—and repeat this four-step sequence eight times in a row.'
    }
  },

  3: {
    name: 'Its so hot in here',
    description: 'Explicitly sexual acts, orgasm‑oriented play, and possible penetration if desired.',
    positions: {
  1:  "Missionary (One partner lies on their back while the other is on top, typically facing them).",
  2:  "Doggy style / rear-entry (One partner is behind the other; the front partner is often on hands-and-knees or leaning forward).",
  3:  "Cowgirl (The receiving partner is on top facing the other partner).",
  4:  "Reverse cowgirl (The receiving partner is on top facing away from the other partner).",
  5:  "Spooning (side-lying, from behind) (Both partners lie on their sides with one behind the other).",
  6:  "Side-by-side (face-to-face) (Partners lie on their sides facing each other).",
  7:  "Seated / lap (One partner sits while the other sits or straddles on their lap).",
  8:  "Standing (Partners remain standing; alignment varies by comfort and height).",
  9:  "Lotus position (A seated, face-to-face hold with close full-body contact).",
  10: "Tabletop (One partner lies back on a raised surface while the other stands or kneels in front).",
  11: "Coital alignment technique (CAT) (A face-to-face variant emphasizing alignment and sustained contact rather than vigorous motion).",
  12: "69 (Partners align so each can give/receive oral at the same time, in opposite directions).",
  13: "Mutual masturbation (no penetration) (Partners stimulate themselves and/or each other with hands).",
  14: "Frottage (non-penetrative rubbing) (Non-penetrative sexual activity involving rubbing bodies/genitals together).",
  15: "Intercrural sex (thigh sex) (Non-penetrative activity involving placement/movement between a partner’s thighs).",
  16: "Tribadism / scissoring (Non-penetrative genital-to-genital rubbing in various body/leg alignments).",
  17: "Butterfly (One partner lies back near the edge of a surface while the other is positioned in front).",
  18: "Wheelbarrow (One partner supports their upper body with hands while the other supports their legs).",
  19: "Bridge (One partner raises their hips/torso in a bridge-like pose while the other partner is positioned in front).",
  20: "Face-to-face standing (Partners stand facing each other in a close embrace)."
},
   modifiers: {
  1:  "Timer block: 60s steady pace, then 15s full stillness, then 45s steady again.",
  2:  "Tempo ladder: switch every 15s (slow → medium → fast → medium).",
  3:  "Stop-start: 10s movement + 5s pause; repeat 6 times.",
  4:  "Pace wave: 20s medium, 20s faster, 20s medium, 20s faster, 10s medium.",
  5:  "Edge-of-control: maintain a strong-but-manageable intensity for 90s without changing tempo.",
  6:  "Micro-pauses: add a 1-second pause after every 8 seconds of movement for the full round.",
  7:  "Breath sync: match inhales/exhales for 30s while continuing the same rhythm; then continue normally.",
  8:  "Counting focus: count down from 30 together (one number per second) while keeping the same rhythm.",
  9:  "Silence rule: no talking for 60s; then normal communication resumes (same pace throughout).",
  10: "Sound-only: for 45s, communicate only with nonverbal sounds (no words) while keeping rhythm steady.",
  11: "Eyes choice: 30s eyes closed + 30s eyes open + 30s either option (keep pace consistent).",
  12: "Hands-only constraint: for 60s, only hands are used; keep tempo steady.",
  13: "No-hands constraint: for 30s, no hands; then 60s normal (same tempo rule throughout).",
  14: "Rhythm mirror: Partner A sets a rhythm for 20s; Partner B mirrors for 20s; repeat once.",
  15: "Pattern rule: repeat “slow-slow-fast” for 60s, then steady medium for 30s.",
  16: "Size shift (non-graphic): keep tempo constant but gradually increase the size of movements for 45s, then gradually decrease for 45s.",
  // Toy-friendly (non-graphic) modifiers
  17: "Vibrator setting ladder: 20s low → 20s medium → 20s high → 30s preferred setting (placement as negotiated).",
  18: "Pulse vs steady: 30s steady mode, 30s pulse mode, 30s steady mode (placement as negotiated).",
  19: "Hand + toy duet: one person maintains a steady rhythm while the other adds a toy for 45s; then swap roles for 45s (same tempo).",
  20: "Finale structure (toy optional): 20s build (slower) → 20s peak (faster) → 20s reset (slower) → 10s stillness; continue at chosen pace."
}

  }
};
