'use strict';
// Phase/location/action tables – edit here

const tables = {
  1: {
    name: 'Warm‑up',
    description: 'Non‑genital, low‑pressure exploration, clothing/lingerie optional.',
    locations: {
      1: 'Lips',
      2: 'Ears (Lobes or Outer Shell)',
      3: 'Nape of the Neck',
      4: 'Collarbone',
      5: 'Shoulders',
      6: 'Nipples / Areolas',
      7: 'Chest / Breasts',
      8: 'Inner Arms / Elbow Crease',
      9: 'Inner Wrists',
      10: 'Palms / Fingertips',
      11: 'Belly Button / Navel',
      12: 'Lower Back / Sacrum',
      13: 'Hips / Waist',
      14: 'Buttocks',
      15: 'Perineum',
      16: 'Inner Thighs',
      17: 'Behind the Knees',
      18: 'Feet / Arches',
      19: 'Primary Genitals',
      20: 'Critical Hit: Roller’s choice of location.'
    },
    actions: {
      1: 'Slow hand strokes: Use the full palm and fingers to make slow, steady strokes over the area.',
      2: 'Feather-light fingertips: Use only the very tips of your fingers to barely graze the surface of the skin.',
      3: 'Gentle kneading: Use the heels of your hands to gently squeeze and knead the muscles in a slow rhythm.',
      4: 'Still hand and breath: Rest a warm hand on the area and breathe slowly together, noticing warmth and contact.',
      5: 'Tracing with one finger: Use a single fingertip to trace lines, shapes, or simple patterns on the skin.',
      6: 'Alternating fingers: Alternate between one finger and all fingers to change the feel of the touch.',
      7: 'Soft tapping: Use the pads of your fingertips to make soft, rhythmic taps over the area.',
      8: 'Cupping with the hand: Gently cup the area with your palm and hold, adding tiny movements if it feels good.',
      9: 'Back of the hand: Use the backs of your fingers or hand to stroke the area for a different texture.',
      10: 'Finger circles: Use one or two fingers to draw slow circles of different sizes over the area.',
      11: 'Warm breath: Blow soft, warm air over the area, occasionally pausing to notice how the skin feels.',
      12: 'Kissing: Place slow, simple kisses on the area, without licking or nibbling.',
      13: 'Soft tongue: Use the tongue to slowly trace short lines or small shapes on the area.',
      14: 'Soft lip pressure: Press your closed lips gently against the area, then slowly release.',
      15: 'Light mouth suction: Use lips to create very gentle suction, then release in a slow rhythm.',
      16: 'Butterfly kisses: Gently flutter your eyelashes against the skin around the area.',
      17: 'Foot strokes (if comfortable): Use the underside of your toes or the ball of your foot to make slow, gentle strokes.',
      18: 'Foot tracing: Use the edge of your foot or toes to trace simple lines or shapes over the area.',
      19: 'Toe taps: Use your toes to make soft, rhythmic taps, similar to fingertip tapping.',
      20: 'Critical success: Spend about twice as long on this location, then roll again on the action table to decide how to touch it.'
    }
  },

  2: {
    name: 'Heating up',
    description: 'Breasts/chest and genitals allowed; still low pressure and exploration‑focused.',
    locations: {
  1: 'Mouth: inner lips and tongue (kissing, licking; no biting).',
  2: 'Ears: lobes and inner rim (gentle breath, lips, or fingers).',
  3: 'Front of neck and under the jawline.',
  4: 'Nape of neck and hairline (back of neck).',
  5: 'Collarbones and upper chest (above the breast/pec line).',
  6: 'Nipples and areolas (any body type; touch or mouth, no penetration).',
  7: 'Nipple–areola complex (same as 6; use for a second focus or reroll for a different location).',
  8: 'Full breast or pectoral mound (including under-breast fold and outer curves).',
  9: 'Lower belly “V” and waistband line toward the pubic hairline (external only).',
  10: 'Pubic mound (mons) and upper groin, above genitals (external only).',
  11: 'Inner thighs, upper third, and groin creases nearest to genitals (external only).',
  12: 'Inner thighs and groin creases (general area).',
  13: 'Buttocks and the crease where butt meets thighs.',
  14: 'Lower back (sacrum) and top of buttocks.',
  15: 'Perineum: the area between genitals and anus (external only).',
  16: 'Outer vulva only (outer lips / labia majora; no penetration).',
  17: 'Penis and scrotum (shaft and balls; touch or mouth, no penetration unless agreed).',
  18: 'Genital “edges”: the skin just beside genitals (where thigh meets groin, or just outside the most sensitive spots).',
  19: 'Hips and hip bones (the bony “handhold” on the sides).',
  20: 'Roller’s choice: pick any Phase 2 location you both want to revisit, or reroll.',
},

    actions: {
  1: 'Use one hand to give 20 straight strokes over the location at a steady pace.',
  2: 'Use one hand: 10 short, rapid strokes, then 10 slow, long strokes; then repeat that whole sequence once.',
  3: 'Use hands to give 15 light brushing strokes, then immediately 15 steadier rubbing strokes over the area.',
  4: 'Use mouth and tongue: 10 slow licks in straight lines, then 10 small circular licks on the location.',
  5: 'Use one hand with lubricant to give 20 smooth, gliding strokes in one continuous motion.',
  6: 'Use fingers or a toy (e.g. dildo or vibrator) to move slowly back and forth 15 times, with a brief pause after every fifth motion.',
  7: 'Use genitals (e.g. grinding or thrusting; penetration only if agreed): 20 slow motions, with one second of stillness after every fourth.',
  8: 'Use hands, mouth, feet, or genitals: steady rhythm for 30s, then faster for 30s, then back to the original steady rhythm for 30s.',
  9: 'The giver uses two body parts at once (e.g. one hand + mouth): one does 10 slow strokes while the other does 10 quick strokes; then swap which is slow and which is quick.',
  10: 'Use hands or genitals to give exactly 10 slow strokes, then 10 medium-speed strokes, then 10 fast strokes, in that order.',
  11: 'Use hands, mouth, feet, or genitals in a three-step pattern: one slow movement, one medium, one fast; repeat that pattern 10 times.',
  12: 'While using hands, mouth, feet, or genitals, give 10 strokes and pair each stroke with an exhale or a small vocal sound (moan, sigh, etc.).',
  13: 'Use hands, mouth, feet, or genitals: “three light touches, then one firmer touch”; repeat that sequence eight times.',
  14: 'Use hands, mouth, feet, or genitals in a stop-start pattern: five movements in a row, then one full second of stillness; repeat that cycle 10 times.',
  15: 'For 60 seconds, use only small circular motions at a constant speed (hands, mouth, feet, or genitals).',
  16: 'While using hands, mouth, feet, or genitals: after every 10 movements, pause briefly and check in with a “green / yellow / red” signal (green = good, yellow = slow down, red = stop); then resume for the next 10.',
  17: 'Keep doing the same action, but every 10 movements make each movement slightly larger (longer or fuller), then continue.',
  18: 'Use hands, mouth, feet, or genitals: do five identical movements, then five quicker, shorter ones; that’s one set. Complete four sets.',
  19: 'Use hands, mouth, feet, or genitals to do 30 tracing movements (about one second each), without pausing.',
  20: 'Use hands, mouth, feet, or genitals: four-step sequence—slow stroke, medium stroke, fast stroke, brief stillness—repeated eight times in a row.'
    }
  },

  3: {
    name: 'Its so hot in here',
    description: 'Explicitly sexual acts, orgasm‑oriented play, and possible penetration if desired.',
    positions: {
  1:  "Missionary: one partner on their back, the other on top facing them.",
  2:  "Doggy style / rear-entry: one partner on hands-and-knees or leaning forward; the other behind.",
  3:  "Cowgirl: receiving partner on top, facing the other (straddling, face-to-face).",
  4:  "Reverse cowgirl: receiving partner on top, facing away from the other.",
  5:  "Spooning: both on their sides, one partner behind the other (spooning from behind).",
  6:  "Side-by-side: both on their sides facing each other.",
  7:  "Seated / lap: one partner sits; the other sits or straddles on their lap (face-to-face or facing away).",
  8:  "Standing: both standing (e.g. one against a wall; alignment depends on height and comfort).",
  9:  "Lotus: seated face-to-face with legs wrapped around each other; close full-body contact.",
  10: "Tabletop: one partner lies back on a bed/table/counter; the other stands or kneels in front.",
  11: "Coital alignment technique (CAT): missionary-style but with bodies shifted so clitoris gets contact; shallow, sustained movement rather than deep thrusting.",
  12: "69: partners head-to-toe so each can give oral to the other at the same time.",
  13: "Mutual masturbation: partners touch themselves and/or each other with hands only (no penetration unless you add it).",
  14: "Frottage: bodies or genitals rubbing together (e.g. between thighs, stomachs, or genitals) with no penetration.",
  15: "Intercrural (thigh sex): thrusting or rubbing between the receiving partner’s closed thighs; no penetration.",
  16: "Tribadism / scissoring: genital-to-genital rubbing (e.g. legs interlocked or overlapping); no penetration.",
  17: "Butterfly: one partner lies on their back with legs bent and feet on the surface (or in the air); the other kneels or stands between the legs.",
  18: "Wheelbarrow: one partner in a plank/push-up position; the other holds their legs (standing or kneeling).",
  19: "Bridge: one partner lifts their hips into a bridge pose (back and shoulders on surface); the other is in front (e.g. for oral or penetration).",
  20: "Standing face-to-face: both standing in a close embrace (e.g. against a wall)."
},
   modifiers: {
  1:  "Timer block: 60s at a steady pace, then 15s of full stillness (no movement), then 45s steady again.",
  2:  "Tempo ladder: every 15s switch tempo—slow, then medium, then fast, then back to medium.",
  3:  "Stop-start: 10s of movement, then 5s pause; repeat that 6 times.",
  4:  "Pace wave: 20s medium, 20s faster, 20s medium, 20s faster, 10s medium.",
  5:  "Edge-of-control: for 90s keep intensity high but still manageable (just under “too much”); don’t change tempo.",
  6:  "Micro-pauses: for the whole round, add a 1-second pause after every 8 seconds of movement.",
  7:  "Breath sync: for 30s match your inhales and exhales while keeping the same rhythm; then continue as you like.",
  8:  "Counting focus: count down from 30 out loud together (one number per second) while keeping the same rhythm.",
  9:  "Silence rule: no talking for 60s (same pace throughout); then you can talk again.",
  10: "Sound-only: for 45s only nonverbal sounds (moans, sighs—no words); keep rhythm steady.",
  11: "Eyes choice: 30s both eyes closed, 30s both eyes open, 30s your choice; keep pace the same.",
  12: "Hands-only: for 60s only hands may be used (no mouth, no toys); keep tempo steady.",
  13: "No-hands: for 30s neither partner uses hands (e.g. bodies only, or mouth/toy); then 60s normal (hands allowed).",
  14: "Rhythm mirror: one partner sets the rhythm for 20s; the other copies it for 20s; then repeat once (swap who leads).",
  15: "Pattern rule: do “slow-slow-fast” for 60s, then steady medium pace for 30s.",
  16: "Size shift: keep tempo the same but for 45s gradually make each movement larger (longer/fuller), then for 45s gradually make them smaller again.",
  17: "Vibrator ladder (if using a toy): 20s low, 20s medium, 20s high, 30s at whoever’s preferred setting (where to use it: agree together).",
  18: "Pulse vs steady (if using a toy): 30s steady vibration, 30s pulse mode, 30s steady (where to use it: agree together).",
  19: "Hand + toy duet: one person keeps a steady rhythm with hands while the other adds a toy for 45s; then swap roles for 45s (same tempo).",
  20: "Finale structure: 20s build (slower), 20s peak (faster), 20s slow down, 10s stillness; then continue at whatever pace you want (toy optional)."
}

  }
};
